"""

Revision ID: 136e4650b91f
Revises: d7ef7e28f07c
Create Date: 2026-01-08 17:32:25.704988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e4650b91f'
down_revision: Union[str, Sequence[str], None] = 'd7ef7e28f07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('semester_id', sa.Integer(), nullable=False))
    op.add_column('courses', sa.Column('department', sa.String(length=64), nullable=False))
    op.add_column('courses', sa.Column('course_number', sa.String(length=16), nullable=False))
    op.add_column('courses', sa.Column('professor', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('courses_title_key'), 'courses', type_='unique')
    op.create_index(op.f('ix_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.create_unique_constraint(None, 'courses', ['department', 'course_number', 'semester_id'])
    op.create_foreign_key(None, 'courses', 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'title')
    op.add_column('students', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.alter_column('students', 'class_year',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('students', 'major',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_students_linkedin'), 'students', ['linkedin'], unique=False)
    op.add_column('studyGroups', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studyGroups', 'capacity')
    op.drop_index(op.f('ix_students_linkedin'), table_name='students')
    op.alter_column('students', 'major',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('students', 'class_year',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('students', 'linkedin')
    op.add_column('courses', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_semester_id'), table_name='courses')
    op.create_unique_constraint(op.f('courses_title_key'), 'courses', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_column('courses', 'professor')
    op.drop_column('courses', 'course_number')
    op.drop_column('courses', 'department')
    op.drop_column('courses', 'semester_id')
    # ### end Alembic commands ###
