"""

Revision ID: 276ca8e44862
Revises: d2fdd13c8cb7
Create Date: 2026-01-08 12:24:31.672213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276ca8e44862'
down_revision: Union[str, Sequence[str], None] = 'd2fdd13c8cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_year', sa.String(length=32), nullable=False))
    op.add_column('students', sa.Column('major', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_students_class_year'), 'students', ['class_year'], unique=False)
    op.create_index(op.f('ix_students_major'), 'students', ['major'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_major'), table_name='students')
    op.drop_index(op.f('ix_students_class_year'), table_name='students')
    op.drop_column('students', 'major')
    op.drop_column('students', 'class_year')
    # ### end Alembic commands ###
