"""

Revision ID: d2fdd13c8cb7
Revises: fef518f2266e
Create Date: 2026-01-08 01:01:54.037591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fdd13c8cb7'
down_revision: Union[str, Sequence[str], None] = 'fef518f2266e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studygroups_email'), table_name='studygroups')
    op.drop_table('studygroups')
    op.add_column('studyGroups', sa.Column('semester_id', sa.Integer(), nullable=False))
    op.add_column('studyGroups', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('studyGroups', sa.Column('meeting_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('studyGroups', sa.Column('meeting_day', sa.String(length=32), nullable=True))
    op.add_column('studyGroups', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_studyGroups_email'), table_name='studyGroups')
    op.create_index(op.f('ix_studyGroups_course_id'), 'studyGroups', ['course_id'], unique=False)
    op.create_index(op.f('ix_studyGroups_semester_id'), 'studyGroups', ['semester_id'], unique=False)
    op.create_foreign_key(None, 'studyGroups', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'studyGroups', 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')
    op.drop_column('studyGroups', 'password_hash')
    op.drop_column('studyGroups', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyGroups', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('studyGroups', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'studyGroups', type_='foreignkey')
    op.drop_constraint(None, 'studyGroups', type_='foreignkey')
    op.drop_index(op.f('ix_studyGroups_semester_id'), table_name='studyGroups')
    op.drop_index(op.f('ix_studyGroups_course_id'), table_name='studyGroups')
    op.create_index(op.f('ix_studyGroups_email'), 'studyGroups', ['email'], unique=True)
    op.drop_column('studyGroups', 'course_id')
    op.drop_column('studyGroups', 'meeting_day')
    op.drop_column('studyGroups', 'meeting_time')
    op.drop_column('studyGroups', 'location')
    op.drop_column('studyGroups', 'semester_id')
    op.create_table('studygroups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('studygroups_pkey'))
    )
    op.create_index(op.f('ix_studygroups_email'), 'studygroups', ['email'], unique=True)
    # ### end Alembic commands ###
