"""

Revision ID: d7ef7e28f07c
Revises: 276ca8e44862
Create Date: 2026-01-08 14:05:55.986949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ef7e28f07c'
down_revision: Union[str, Sequence[str], None] = '276ca8e44862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyGroups', sa.Column('isPrivate', sa.Boolean(), nullable=False))
    op.add_column('studyGroups', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_studyGroups_owner_id'), 'studyGroups', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'studyGroups', 'students', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studyGroups', type_='foreignkey')
    op.drop_index(op.f('ix_studyGroups_owner_id'), table_name='studyGroups')
    op.drop_column('studyGroups', 'owner_id')
    op.drop_column('studyGroups', 'isPrivate')
    # ### end Alembic commands ###
