"""

Revision ID: f73de209dff3
Revises: c518dd295675
Create Date: 2026-01-07 22:30:35.923207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73de209dff3'
down_revision: Union[str, Sequence[str], None] = 'c518dd295675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_token', sa.String(), nullable=False))
    op.add_column('sessions', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_sessions_email'), table_name='sessions')
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_student_id'), 'sessions', ['student_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sessions', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_student_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.create_index(op.f('ix_sessions_email'), 'sessions', ['email'], unique=True)
    op.drop_column('sessions', 'expires_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'student_id')
    op.drop_column('sessions', 'session_token')
    # ### end Alembic commands ###
