name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build JAR
      run: ./mvnw clean package -DskipTests
      working-directory: bearnet.api
    
    - name: Build Docker image
      run: docker build -t bearnet-api:latest .
      working-directory: bearnet.api
